#! /usr/bin/env bash

display_config() {
  echo "required environment variables"
  echo "EFI_PARTITION: ${EFI_PARTITION}"
  echo "LINUX_PARTITION: ${LINUX_PARTITION}"
  echo "LINUX_DRIVE: ${LINUX_DRIVE}"

  [ -z ${EFI_PARTITION} ] && exit 10
  [ -z ${LINUX_PARTITION} ] && exit 11
  [ -z ${LINUX_DRIVE} ] && exit 12
}

display_config

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

[ `whoami` = root ] && echo must not be run as root && exit 10

mount_point=/grub-reinstall-mountpoint
system_folders_required='/dev /dev/pts /proc /sys'

# mount linux partition
sudo mkdir -p ${mount_point}
sudo mount -t ext4 ${LINUX_PARTITION} ${mount_point} || true

# mount folders for chroot
for d in ${system_folders_required}
do
  sudo mount --bind $d ${mount_point}${d} || true
done

# display chroot commands and chroot
echo "run:"
echo "mount ${EFI_PARTITION} /boot/efi"
echo "grub install ${LINUX_DRIVE}"
echo "grub-install --recheck ${LINUX_DRIVE}"
echo "update-grub"
echo "exit"

sudo chroot ${mount_point}

# unmount folders for chroot
for d in ${system_folders_required}
do
  sudo umount ${mount_point}$d || true
done

# needed because we're monting /dev/pts
sudo umount ${mount_point}/dev
